# Generated by Django 4.2.16 on 2024-09-11 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_shoe_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='condition',
            new_name='current_ondition',
        ),
        migrations.RenameField(
            model_name='shoe',
            old_name='name',
            new_name='model',
        ),
    ]
