# Generated by Django 4.2.16 on 2024-09-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_rename_condition_shoe_current_ondition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='current_ondition',
            new_name='current_condition',
        ),
    ]
