# Generated by Django 4.2.16 on 2024-09-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_rename_current_ondition_shoe_current_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
