# Generated by Django 4.2.16 on 2024-09-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_shoe_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='shoe',
            name='photo',
            field=models.ImageField(blank=True, upload_to='shoes/'),
        ),
    ]
