# Generated by Django 4.2.16 on 2024-09-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_lace_alter_shoe_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='laces',
            field=models.ManyToManyField(to='my_app.lace'),
        ),
    ]
