# Generated by Django 4.2.16 on 2024-09-16 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_cleaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='shoe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.shoe'),
            preserve_default=False,
        ),
    ]
